services:
  backend:
    build: .
    env_file:
      - stack.env
    ports:
      - "${PORT}:${PORT}"
    container_name: xp-keh
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.120
    environment:
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - MINIO_CONTAINER=${MINIO_CONTAINER}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_WEATHER_ACCESS_KEY=${MINIO_WEATHER_ACCESS_KEY}
      - MINIO_WEATHER_SECRET_KEY=${MINIO_WEATHER_SECRET_KEY}
      - MINIO_SEISMIC_ACCESS_KEY=${MINIO_SEISMIC_ACCESS_KEY}
      - MINIO_SEISMIC_SECRET_KEY=${MINIO_SEISMIC_SECRET_KEY}
      - MINIO_READER_ACCESS_KEY=${MINIO_READER_ACCESS_KEY}
      - MINIO_READER_SECRET_KEY=${MINIO_READER_SECRET_KEY}
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: backend-redis
    ports:
      - "6382:6379"
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.121

networks:
  nginx-manager_customnetwork:
    external: true
