version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    command: npm start
    networks:
      data-station-network:
        ipv4_address: 172.20.14.90

networks:
  data-station-network:
    external: true
