services:
  backend:
    build: .
    ports:
      - "${PORT}:${PORT}"
    networks:
       data-station-network:
         ipv4_address: 172.20.14.91
    environment:
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
   data-station-network:
     external: true