services:
  backend:
    build: .
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: production
    command: npm start
    networks:
      data-station-network:
        ipv4_address: 172.20.14.91

networks:
  data-station-network:
    external: true
