services:
  backend:
    build: .
    env_file:
      - stack.env
    ports:
      - "${PORT}:${PORT}"
    networks:
       data-station-network:
         ipv4_address: 172.20.14.91
    environment:
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:${PORT}/health"]

networks:
   data-station-network:
     external: true