services:
  backend:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/usr/src/app
    restart: always

volumes:
  clickhouse_data: