services:
  backend:
    build: .
    env_file:
      - stack.env
    ports:
      - "${PORT}:${PORT}"
    container_name: xp-keh
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.120
    environment:
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - MINIO_ENDPOINT=http://node1:9000 #TODO: put to env var
      - MINIO_ACCESS_KEY=userRead
      - MINIO_SECRET_KEY=dataReader
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: backend-redis
    ports:
      - "6382:6379"
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.121

networks:
  nginx-manager_customnetwork:
    external: true
