services:
  backend:
    build: .
    env_file:
      - stack.env
    ports:
      - "${PORT}:${PORT}"
    container_name: xp-keh
    networks:
      data-station-network:
        ipv4_address: 172.20.14.91
    environment:
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:${PORT}/health"]

  redis:
    image: redis:latest
    container_name: backend-redis
    ports:
      - "6382:6379"
    networks:
      - data-station-network

networks:
  data-station-network:
    external: true
