services:
  backend:
    build: .
    env_file:
      - stack.env
    ports:
      - "${PORT}:${PORT}"
    container_name: xp-keh
    networks:
      nginx_manager_customnetwork:
        ipv4_address: 172.20.0.120
    environment:
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: backend-redis
    ports:
      - "6382:6379"
    networks:
      - data-station-network

networks:
  nginx_manager_customnetwork:
    external: true
